export const ANIM = {
  CARD_IN_DURATION: 0.25,
  CARD_OUT_DURATION: 0.2,
  CARD_BOUNCE_DURATION: 0.12,
  TIMER_FLASH_DURATION: 0.15,
  HYPE_GLOW_DURATION: 0.8,
  BANNER_DURATION: 2.5,
  LOW_TIME_THRESHOLD: 10,
  MID_TIME_RATIO: 0.3,
  GAME_OVER_DELAY: 0.65,
  ADD_POP_DURATION: 0.18,
};
